### ISSUE TITLE
Query about Data Augmentation in Meta World Environments

### ISSUE THREAD

**Issue by yiwenzhu-evan** [huxiao09/QPA#1]
![image](https://github.com/huxiao09/QPA/assets/49807276/e5895ca5-104b-4196-a884-7c5bcf880a91)

I'm interested in understanding the rationale behind not incorporating data augmentation techniques in the meta world environments. Specifically, I noticed that in the function self.reward_model.train_reward(), there isn't a parameter for data augmentation like data_aug_ratio, which is used in self.reward_model.train_reward_iter(num_iters).

Does this imply that methods without data augmentation perform better in meta world environments, or is there another reason for this design choice?

Thank you for your insights!

**Comment by huxiao09** [comment]
Hello! The data augmentation technique is borrowed from SURF (Park et al., 2022). Empirically, I found that this technique doesn't significantly impact performance in our meta-world environments. Therefore, in this code I have chosen not to use data augmentation for meta world.

Thank you for your attention!

**Comment by huxiao09** [comment]
Hello! The data augmentation technique is borrowed from SURF (Park et al., 2022). Empirically, I found that this technique doesn't significantly impact performance in our meta world environments. Therefore, in this code I have chosen not to use data augmentation for meta world.

Thank you for your attention!
